### ISSUE TITLE
Can't watch products

### ISSUE THREAD

**Issue by luongs3** [aimeos/aimeos-laravel#155]
When access a detail site of a certain product. I clicked "watch" but nothing happens
http://laravel.demo.aimeos.org/default/en/EUR/detail/10019/Demo_article/0

**Comment by aimeos** [comment]
Thank you for the hint! It works if you are logged in but in case you are not, you should be redirected to the login screen. We will fix that behavior

**Comment by aimeos** [comment]
Laravel tries to guess the format it should return instead of responding with the login page. This is fixed with this commit: https://github.com/aimeos/ai-client-html/commit/52d8f02d6bc368f73a233391cbfbc1c4f954285b

An updated version is available and has been installed on the demo server. Thanks again!
