### ISSUE TITLE
don't use my own extention src folder in jqadm?

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#191]
i have my own custom extension, in admin/jqadm project use my own templates but for src it reffer to ai-admin-jqadm src folder?
what must I do to project use my custom extention src folder?

**Comment by aimeos** [comment]
The src folder is used but you can't overwrite classes the same way was templates because composer will not know which class would be the right one if both are named the same. Instead, you have to name your class e.g. "Myclass" and configure your new class name in `./admin/jqadm/config/admin.php`. To make that work, you have to add `admin/jqadm/config` to the "config" section of your `manifest.php`.

You own class name has to be configured like in the frontend, e.g. `admin/jqadm/product/name` for the product panel. Here's an example documentation:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/src/Admin/JQAdm/Product/Factory.php#L34

**Comment by parsester** [comment]
my extention src folder (client/html/src) not working for me, i change my own extention client/html/src/Client/Html/Checkout/Standard/Address/Billing/Standard mandentory fields but is not work for me, why? what should i do?

**Comment by parsester** [comment]
how can i do for force app to use just my own extension classes, templates, and other, and don't check or use default ai extensions,
i have 2 question:
1- if i change (classes and templates ai-client-html or other ai- extentiosns to customize them to fit my needs, after that if aimeos release new version and i upgrade that according to the [upgrade process instructions](https://aimeos.org/docs/Laravel/Upgrade), **Will my changes go away?**
2- i have my own extension, I copy classes and templates from ai- default extensions to my extension, my templates overwrite standard templates but my classes not, i want to app use my extention classes and don't check or use default ai extentions, and when new version of aimeos laravel released, accourding to [Aimeos changelog](https://aimeos.org/docs/Developers/Changelog) make changes to my own extention templates and classes, Is it possible؟

**Comment by aimeos** [comment]
1.) Don't change files in the ai-* extensions. They will be overwritten on update

2.) Overwrite classes in own extension:
- Copy the class into the same directory structure in your own extension
- Rename your file to "Myproject.php" and the class to "Myproject"
- Change the code in the method you need
- Remove all unchanged methods and properties
- Create `./admin/jqadm/config/admin.php` with:
```
return [
  'jqadm' => [
    'product' => [
       'name' => 'Myproject'
    ]
  ]
];
```
- Add to `admin/jqadm/config` to `config` section of your `manifest.php`:
```
  'config' => [
    'admin/jqadm/config',
    ...
  ]
```
