### ISSUE TITLE
Upgrade to Bootstrap v4.0.0 in the Admin UI

### ISSUE THREAD

**Issue by dev7ch** [aimeos/aimeos-laravel#218]
Hola Aimeos Folks,

first of all, i would let the let you know that we took a closer look since a few weeks to some modern shop applications, we decided to use aimeos to build a multisite shop prototype with automated deployment and complete automated rollout/setup scripts, now the prototype working super on multiple hostings and stages via git repo  👍 

We see your application as pretty forwarding, thank for your beautiful open source contribution including microdata following shema.org!!!

Here are the Questions:

- The frontend uses Bootstrap 3 which doesn't matter because it will be replaced completely, but there are planes to upgrade it to BS v4 ?

- The Admin uses BS4 alpha-6, do i am only using the wrong release or is the Admin UI not updated to BS4 stable release? Is upgrading planned or already done?

- How flexible I am in general with the frontend of the Admin UI? can i simply use vue or relpace BS 4 aplha-6 by my self?

Until now I have read only the README in this Repo and I am New to Laravel (coming from yii2)

**Comment by dev7ch** [comment]
https://github.com/aimeos/aimeos-laravel/blob/master/src/views/admin/index.blade.php

**Comment by dev7ch** [comment]
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/ShopServiceProvider.php#L22

Maybe extending here an abstract Class which is placed outside of the vendor folder enable more flexibility to control the views of the admin UI, just guessing.

**Comment by aimeos** [comment]
We would like to use BS4 for the admin interface in the next release. If you are able to create a PR, this would be great! :-)

The frontend still uses BS3 because there are much more themes for this version than for BS4. Maybe we can switch to BS4 in the 2019.01 release.

Vue.JS is already used in the admin interface for price/text/image panels. You can replace the existing templates if you want. The admin templates can be overwritten in the same way as in the frontend. Place them in the admin/jqadm/templates/* directory of your own extension.

You can also add new panels or remove existing ones - just as you need. It's all done by configuration: https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/config/admin.php

**Comment by dev7ch** [comment]
@aimeos thank you for the prompt Sunday relpy, that sounds good :)

Yes, i ll give it a try and i already started to setup a dev and testing repo and as soon as there is soth to show i ll come back to you.

https://github.com/dev7ch/aimeos-laravel-bs4-test

Btw. Due this more a feature request like an issue shall i close it?
Do you have a slackroom for sth like a "aimeos community"?

**Comment by aimeos** [comment]
There's no Slack channel for Aimeos yet. You can use Github for feature requests and pull requests or ask questions in our forum: https://aimeos.org/help

**Comment by karneaud** [comment]
Hello,

Looking into this as well for #AdminLTE  how easy is it to replace the current admin theme and have you guys considered [Stylist](https://github.com/floatingpointsoftware/stylist)  to make themes more modular?

**Comment by aimeos** [comment]
We did not use AdminLTE directly because it requires HTML structure changes too. Instead, we had adapted the styles from AdminLTE to our generic HTML. If you want to change the look of the admin interface, you mainly have to change the CSS.

Regarding Stylist: It's a Laravel only package and not portable so we can't use it because Aimeos is also available for other frameworks.
