### ISSUE TITLE
Many times stag image automatically gets visible on the product page and category page: Is it bug or cache problem?

### ISSUE THREAD

**Issue by parasbhadauria** [aimeos/aimeos-laravel#350]
Hi,
Many times stag image automatically gets visible on the product page and category page.
You can look into the attached screenshot
Is this happening because of cache problem ?
Please help me to sort it out.
Thanks
![product page](https://user-images.githubusercontent.com/75558471/101273393-f9d71800-37ba-11eb-8d55-ae4589d2e991.jpg)

**Comment by aimeos** [comment]
This happens because you have a stage image assigned to a category and jump from this category to a product page. Then, the stage image for that category is shown in the detail page. You can either remove the stage image from the category or you can remove the catalog/stage component from the detail page in the "page" section of your ./config/shop .php file
