### ISSUE TITLE
Error 'Item with ID "1" in "customer.id" not found' when setting up multisite

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/aimeos-laravel#383]
Hi Aimeos,

I'm trying to setup multi site for aimeos+laravel
So far everything's working except following scenario

1. using single database, setup 2 domains
 - example1.com
 - example2.com

2. Register user1 at example1.com
3. Without registering at example2.com, browse example2.com with user1 login.
All Aimeos components will become `Item with ID "1" in "customer.id" not found`

I'm not sure is it a bug or does it require the marketplace extension?

I just want to build multiple site with single database, shared login, so that customer just have to register once and login to all sites.

**Comment by aimeos** [comment]
The problem is that when a merchant registers (this is the standard setup), the ID of the newly created site is assigned to his accout so he can log in into the backend for his site. If this merchant changes to another site (example2.com), Laravel knows he is still logged in due to the session but retrieving the user data is impossible because the site ID is different than the one stored in his user account.

**Comment by switch-cheehau** [comment]
I see, but the site ID we can get based on domain and mshop_locale_site, am i correct?

Because if does not allow, meaning customer can only register at one of the sites. If he/she try to register to another site, the username/email will be duplicated.

**Comment by aimeos** [comment]
> I see, but the site ID we can get based on domain and mshop_locale_site, am i correct?

Yes, the site ID is bound to the domain in your case.

> Because if does not allow, meaning customer can only register at one of the sites. If he/she try to register to another site, the username/email will be duplicated.

These are two different things. If customers (not vendors) register otherwise, they can get an account without site ID and these account is available at all sites. Only vendors need an account with a site ID and it's not possible to have a vendor account without site ID because then, they will be normal users.

**Comment by switch-cheehau** [comment]
Ah. I see. Understand.
I never thought siteId can be null. Make sense now. Will test it out and close the issue afterward. Thanks!!

**Comment by switch-cheehau** [comment]
Tested, it's working perfectly. I'll close the issue. Thanks for the tips
