### ISSUE TITLE
Pricing rules issue, getting reset after placing order

### ISSUE THREAD

**Issue by damanmokha** [aimeos/aimeos-laravel#494]
I am using the Aimeos headless distribution and have set up a pricing rule for administrators that provides a 50% discount for certain categories. While the pricing rule is correctly applying a 50% discount when adding items to the basket via the API, I've encountered two issues:

1. The rebate value appears to be empty for the affected product. For example, if the original price of a product was $20, after being added to the cart, it is correctly showing a discounted price of $10, but the rebate value is displayed as 0. This lack of rebate information makes it unclear whether the discount has been applied or not.
2. After placing an order using the basket API, upon returning from the API with the order details, I've noticed that only one product in the order reflects the offered discounted price. The remaining products seem to have reverted to their original prices.

**Environment Details:**
1. Aimeos Headless Distribution Version: 2023.04.*
2. Operating System: (Mac, Linux)

**Comment by aimeos** [comment]
> 1. The rebate value appears to be empty for the affected product. For example, if the original price of a product was $20, after being added to the cart, it is correctly showing a discounted price of $10, but the rebate value is displayed as 0. This lack of rebate information makes it unclear whether the discount has been applied or not.

A dynamic pricing rule is not a rebate in Aimeos per definition so the rebate field stays empty in that case. Otherwise, the customer would be shown a rebate value in the basket of the HTML frontend.

> 2. After placing an order using the basket API, upon returning from the API with the order details, I've noticed that only one product in the order reflects the offered discounted price. The remaining products seem to have reverted to their original prices.

Can you confirm that the price change is applied to every product after you add it to the basket via API?

> 1. Aimeos Headless Distribution Version: 2023.04.*

You *should* upgrade to 2023.07 as your version isn't supported actively any more and you *must* upgrade to 2023.10 LTS when it's released in October.
