### ISSUE TITLE
Using eloquent for working with DB of mshop bad idea?

### ISSUE THREAD

**Issue by Jossnaz** [aimeos/aimeos-laravel#56]
Using eloquent for working with DB of mshop is bad idea?

e.g. do you guys often makes changes to the database with releases and thus making the eloquent classes I would create broken? in other words, is it highly disencouraged  to create my own eloquent models for your stuff?

**Comment by aimeos** [comment]
Yes, it's a really bad idea but not because we change the tables so often (that happens once a year). The reasons are:
- 3rd party extensions can add new columns to tables if necessary
- You will loose the ability to store domain data (index, products, orders, etc.) in another database or in a document oriented server like Elasticsearch and thus preventing your application to scale
- The managers/items are optimized for speed and to easily get compound data, e.g.
```
$manager->searchItems( $criteria, array( 'text', 'price', 'media', 'attribute' ) );
```
will return all products including texts, prices, images and attributes. Using Eloquent, you need at least nine queries to get the same
