### ISSUE TITLE
Infinity loading in admin page

### ISSUE THREAD

**Issue by knoonrx** [aimeos/aimeos-laravel#8]
Hi folks I make my first instalation of aimeos in a test enviroment, but when I go to the admin page I see the loading gif image show infinity for me.

And I'm unable to perform anything on administrator area.

Is there something that I made wrong, or something that I miss?

Thank You ;)

http://s8.postimg.org/6ot3vd4qt/Captura_de_tela_de_2015_07_23_14_51_00.png

**Comment by aimeos** [comment]
Can you please open the web console and see what the HTTP response code of the request is?
If you are using 1.0.x (not dev-master or 1.1.x released today) I assume that you didn't deactivated the CSRF middleware: https://aimeos.org/docs/Laravel/Install_Aimeos#Version_1.0.x

This is not necessary any more when using 1.1.0 or dev-master because it contains full CSRF protection support.

**Comment by knoonrx** [comment]
Thank you again problem solved.
