### ISSUE TITLE
[Aimeos\MW\DB exception] import demo failed - specified key was too long

### ISSUE THREAD

**Issue by aouliet** [aimeos/aimeos-laravel#80]
An exception occurred while executing statement create index user_status_address1_address2_index on users.

I 've followed the installation guide step by step https://github.com/aimeos/aimeos-laravel#installation-or-update

env('DB_CONNECTION', 'mysql'),

**Comment by aimeos** [comment]
Please post the stack trace of the exception and the Laravel/Aimeos version you use

**Comment by aouliet** [comment]
` [Aimeos\MW\DB\Exception]
  Executing statement "CREATE INDEX users_status_address1_address2_index ON u
  sers (status, address1, address2)" failed: An exception occurred while exec
  uting 'CREATE INDEX users_status_address1_address2_index ON users (status,
  address1, address2)':
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes`

aimeos/ai-laravel: ~2016.10
Laravel version : 5.2.45

**Comment by aouliet** [comment]
Full Stack trace:
#0 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Task/Base.php(138): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-core/lib/mshoplib/setup/TablesCreateMShop.php(151): Aimeos\MW\Setup\Task\Base->executeList(Array, 'db-customer')
#2 /home4/theaisaf/tgmaxx/ext/ai-laravel/lib/custom/setup/TablesCreateLaravel.php(42): Aimeos\MW\Setup\Task\TablesCreateMShop->setupSchema(Array)
#3 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(203): Aimeos\MW\Setup\Task\TablesCreateLaravel->migrate()
#4 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(197): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array, Array)
#5 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(197): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array, Array)
#6 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(111): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array)
#7 /home4/theaisaf/tgmaxx/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/SetupCommand.php(106): Aimeos\MW\Setup\Manager\Multiple->migrate(NULL)
#8 [internal function]: Aimeos\Shop\Command\SetupCommand->fire()
#9 /home4/theaisaf/tgmaxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#10 /home4/theaisaf/tgmaxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#11 /home4/theaisaf/tgmaxx/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home4/theaisaf/tgmaxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home4/theaisaf/tgmaxx/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home4/theaisaf/tgmaxx/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Aimeos\Shop\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home4/theaisaf/tgmaxx/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home4/theaisaf/tgmaxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home4/theaisaf/tgmaxx/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
[2016-11-23 09:59:42] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Aimeos\Shop\ShopServiceProvider' not found' in /home4/theaisaf/tgmaxx/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146

**Comment by aimeos** [comment]
What database are you using and which version?

**Comment by aouliet** [comment]
Mysql ver 5.5.51-38.2

**Comment by aimeos** [comment]
MySQL seems to enforce an index limit of 1000 bytes in newer version which are compiled for 32bit platforms: http://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes

The size of the index is actually 6 + 255 * 3 + 255 * 3 = 1542 due to using UTF-8.
We have to find a way now that also works for PostgreSQL and the other database servers :-/

**Comment by aouliet** [comment]
weird .. Anyway I'm gonna try without demo data then

**Comment by aimeos** [comment]
You can remove the index in the migration file until we've found a solution

**Comment by aouliet** [comment]
Ok !

**Comment by aimeos** [comment]
Can you try the dev-master branch? We've made some changes that should fix the issue.
It might be necessary to start from scratch

**Comment by aouliet** [comment]
using dev-master branch, i get :

> Can't locate path: </home4/user/tgmaxxaimeos/vendor/aimeos/aimeos-laravel/src/database/migrations>

**Comment by nehuljain** [comment]
same error again and again !!
how to solve it !

**Comment by aimeos** [comment]
You need to use
```
"aimeos/aimeos-laravel": "dev-master"
```
in your composer.json and execute `composer update` to use the current development branch. It contains the necessary changes.

**Comment by nehuljain** [comment]
[Aimeos\MW\DB\Exception]
Executing statement "CREATE INDEX users_status_address1_address2_index ON
users (status, address1, address2)" failed: An exception occurred while ex
ecuting 'CREATE INDEX users_status_address1_address2_index ON users
(status, address1, address2)':
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was
too long; max key length is 1000 bytes



php artisan aimeos:setup

this is the error whenever I am running   {{         php artisan
aimeos:setup            }}


while installing aimeos, please try helping me out !!

i have been stuck here since 4 days.

**Comment by aimeos** [comment]
Please post the output of `composer show -i`

**Comment by nehuljain** [comment]
C:\wamp\www\home>composer show -i


Key require is a duplicate in ./composer.json at line 16
You are using the deprecated option "installed". Only installed packages
are shown by default now. The --all option can be used to show all packages.
aimeos/ai-admin-extadm                2016.10.2  Aimeos ai-admin-extadm
extension
aimeos/ai-admin-jqadm                 2016.10.3  Aimeos ai-admin-jqadm
extension
aimeos/ai-admin-jsonadm               2016.10.1  Aimeos ai-admin-jsonadm
extension
aimeos/ai-client-html                 2016.10.12 Aimeos ai-client-html
extension
aimeos/ai-controller-frontend         2016.10.6  Aimeos
ai-controller-frontend extension
aimeos/ai-controller-jobs             2016.10.3  Aimeos ai-controller-jobs
extension
aimeos/ai-gettext                     2016.10.1  Aimeos Gettext extension
aimeos/ai-laravel                     2016.10.2  Laravel adapter for Aimeos
web shops and e-commerce solutions
aimeos/ai-swiftmailer                 2016.10.1  SwiftMailer adapter for
Aimeos web shops and e-commerce solutions
aimeos/aimeos-core                    2016.10.6  Full-featured e-commerce
components for high performance online shops
aimeos/aimeos-laravel                 2016.10.3  Full-featured Laravel web
shop package and e-commerce solution for high performance shops
classpreloader/classpreloader         3.1.0      Helps class loading
performance by generating a single PHP file containing all of the
autoloaded f...
composer/installers                   v1.2.0     A multi-framework Composer
library installer
dnoegel/php-xdg-base-dir              0.1        implementation of xdg base
directory specification for php
doctrine/annotations                  v1.3.0     Docblock Annotations Parser
doctrine/cache                        v1.6.1     Caching library offering
an object-oriented API for many cache backends
doctrine/collections                  v1.3.0     Collections Abstraction
library
doctrine/common                       v2.6.2     Common Library for
Doctrine projects
doctrine/dbal                         v2.5.5     Database Abstraction Layer
doctrine/inflector                    v1.1.0     Common String
Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5      A small, lightweight
utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1     Base library for a lexer
that can be used in Top-Down, Recursive Descent Parsers.
fzaninotto/faker                      v1.6.0     Faker is a PHP library
that generates fake data for you.
hamcrest/hamcrest-php                 v1.2.2     This is the PHP port of
Hamcrest Matchers
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jeremeamia/SuperClosure               2.3.0      Serialize Closure objects,
including their context and binding
laravel/framework                     v5.3.28    The Laravel Framework.
league/flysystem                      1.0.32     Filesystem abstraction:
Many filesystems, one API.
mockery/mockery                       0.9.7      Mockery is a simple yet
flexible PHP mock object framework for use in unit testing with PHPUnit,
P...
monolog/monolog                       1.22.0     Sends your logs to files,
sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.1.0     CRON for PHP: Calculate
the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                     1.5.5      Create deep copies
(clones) of your objects
nesbot/carbon                         1.21.0     A simple API extension for
DateTime.
nikic/php-parser                      v3.0.2     A PHP parser written in PHP
paragonie/random_compat               v2.0.4     PHP 5.x polyfill for
random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common       1.0        Common reflection classes
used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1      With this component, a
library can provide support for annotations via DocBlocks or otherwise
retr...
phpdocumentor/type-resolver           0.2.1
phpspec/prophecy                      v1.6.2     Highly opinionated mocking
framework for PHP 5.3+
phpunit/php-code-coverage             4.0.4      Library that provides
collection, processing, and rendering functionality for PHP code coverage
in...
phpunit/php-file-iterator             1.4.2      FilterIterator
implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     1.0.8      Utility class for timing
phpunit/php-token-stream              1.4.9      Wrapper around PHP's
tokenizer extension.
phpunit/phpunit                       5.7.4      The PHP Unit Testing
framework.
phpunit/phpunit-mock-objects          3.4.3      Mock Object library for
PHPUnit
psr/http-message                      1.0.1      Common interface for HTTP
messages
psr/log                               1.0.2      Common interface for
logging libraries
psy/psysh                             v0.8.0     An interactive shell for
modern PHP.
ramsey/uuid                           3.5.2      Formerly rhumsaa/uuid. A
PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universal...
sebastian/code-unit-reverse-lookup    1.0.0      Looks up which function or
method a line of code belongs to
sebastian/comparator                  1.2.2      Provides the functionality
to compare PHP values for equality
sebastian/diff                        1.4.1      Diff implementation
sebastian/environment                 2.0.0      Provides functionality to
handle HHVM/PHP environments
sebastian/exporter                    2.0.0      Provides the functionality
to export PHP variables for visualization
sebastian/global-state                1.1.1      Snapshotting of global
state
sebastian/object-enumerator           2.0.0      Traverses array structures
and object graphs to enumerate all referenced objects
sebastian/recursion-context           2.0.0      Provides functionality to
recursively process PHP variables
sebastian/resource-operations         1.0.0      Provides a list of PHP
built-in functions that operate on resources
sebastian/version                     2.0.1      Library that helps with
managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v5.4.4     Swiftmailer, free
feature-rich PHP mailer
symfony/console                       v3.1.8     Symfony Console Component
symfony/css-selector                  v3.1.8     Symfony CssSelector
Component
symfony/debug                         v3.1.8     Symfony Debug Component
symfony/dom-crawler                   v3.1.8     Symfony DomCrawler
Component
symfony/event-dispatcher              v3.2.1     Symfony EventDispatcher
Component
symfony/finder                        v3.1.8     Symfony Finder Component
symfony/http-foundation               v3.1.8     Symfony HttpFoundation
Component
symfony/http-kernel                   v3.1.8     Symfony HttpKernel
Component
symfony/polyfill-mbstring             v1.3.0     Symfony polyfill for the
Mbstring extension
symfony/polyfill-php56                v1.3.0     Symfony polyfill
backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.3.0     Symfony utilities for
portability of PHP codes
symfony/process                       v3.1.8     Symfony Process Component
symfony/routing                       v3.1.8     Symfony Routing Component
symfony/translation                   v3.1.8     Symfony Translation
Component
symfony/var-dumper                    v3.1.8     Symfony mechanism for
exploring and dumping PHP variables
symfony/yaml                          v3.2.1     Symfony Yaml Component
vlucas/phpdotenv                      v2.4.0     Loads environment
variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.2.0      Assertions to validate
method input/output with nice error messages.
zendframework/zend-diactoros          1.3.7      PSR HTTP Message
implementations

C:\wamp\www\home>

**Comment by aimeos** [comment]
Seems like you have both lines in your composer.json:
```
"aimeos/aimeos-laravel": "~2016.10"
...
"aimeos/aimeos-laravel": "dev-master"
```
Remove the line with `2016.10` and execute `composer update` again

**Comment by nehuljain** [comment]
i got same error again  ...and also you guide me about pasting the array as
i think this can be the fault..i am pasting  Aimeos\Shop\ShopServiceProvider
::class, only this portion  like this
rviceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Aimeos\Shop\ShopServiceProvider::class,
    ],

return array(    'providers' => array(        ...
Aimeos\Shop\ShopServiceProvider::class,    ),);

**Comment by aimeos** [comment]
You can't just copy and paste the examples and you need some basic knowledge of PHP and Laravel.

**Comment by nehuljain** [comment]
yes ..you are right ! but we can experiment a little if things don't work !
specially when you are on tanning ! :)

**Comment by idemsisvoje** [comment]
I tried with master-dev, 2017.01 and 2017.02 but I still get the Specified key was too long error when installing demo data. Any suggestions please?

**Comment by aimeos** [comment]
Maybe this article can help:
http://geektnt.com/laravel-5-4-migration-unique-key-is-too-long.html

**Comment by idemsisvoje** [comment]
Thanks a lot, updating mysql version and changing the database collation solved the problem.

**Comment by becology1100** [comment]
i have the same error and have no solutions ?! anyone can help ?!!

**Comment by aimeos** [comment]
Did you read this?
https://github.com/aimeos/aimeos-laravel#important-notice
