### ISSUE TITLE
Missing argument 3 for App\Providers\AuthServiceProvider::App\Providers\

### ISSUE THREAD

**Issue by developerpratika** [aimeos/aimeos-laravel#91]
after login i am getting this error in 5.3 

Missing argument 3 for App\Providers\AuthServiceProvider::App\Providers\{closure}(), called in D:\xampp\htdocs\test5_3\vendor\laravel\framework\src\Illuminate\Auth\Access\Gate.php on line 265 and defined

can you help me

i follow all the  steps
 `"aimeos/aimeos-laravel": "2017.01.*"`

For Laravel 5.3
```
public function boot()
{
    // Keep the lines before

    Gate::define('admin', function($user, $class, $roles) {
        return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );
    });
   $this->registerPolicies();
}
```
now what i do

**Comment by developerpratika** [comment]
i changed to 
 ```
Gate::define('admin', function($user, $roles) {
        return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );
        });
```
now it is working why

**Comment by aimeos** [comment]
The problem is a change in Laravel 5.4 auth system that now requires the class name of object for authentication. We've updated so code to work with Laravel 5.4 in dev-master but the documentation was misleading at that point. Now we've pushed the changed into the 2017.01 branch, made a new release and updated the README.

If you execute `composer update`, you will get version 2017.01.2 where you need the second `class` argument again when using Laravel 5.3.

**Comment by developerpratika** [comment]
ok thanks
